Layout/LineLength:
  Max: 140
  Exclude:
    - 'benchmarks/*.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - Rakefile

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'benchmarks/*.rb'
    - Rakefile

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Style/Semicolon:
  Exclude:
    - 'benchmarks/*.rb'

Style/NumericPredicate:
  Exclude:
    - 'benchmarks/*.rb'

Style/MixinUsage:
  Exclude:
    - Rakefile

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/rubocop/**/*.rb
