inherit_from: .rubocop-todo.yml
plugins:
  - rubocop-rspec

AllCops:
  NewCops: disable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'database_validations.gemspec'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'gemfiles/**/*'

Naming/FileName:
  Exclude:
    - 'lib/rubocop-database_validations.rb'
    - 'example/Gemfile'
    - 'example/Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false


Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'benchmarks/*.rb'
